### ISSUE TITLE
Anzeigen eines Pokemons

### ISSUE THREAD

**Issue by geekmaedchen** [geekmaedchen/pokelist#1]
## Value statement
As a **user** 
I need **a list of pokemon with a checkbox** 
so that **the user can mark the pokemon he/she want to trade** 
## Description (Text, Scribble, Wireframe, Design)
A pokemon is shown in a list and has a checkbox.
<img width="553" alt="grafik" src="https://user-images.githubusercontent.com/53256699/69544473-162d5b80-0f90-11ea-8da9-d1674fbd4fad.png">

## Acceptance criteria
- [x] List item for a Pokemon is shown
- [x] Basic info of Pokemon is shown
- [x] Tags for Types of Pokemon are shown separately
- [x] Checkbox is shown
## Tasks
- [x] Create an App component with GlobalStyle
- [x] Create a component PokemonUserList
- [x] Create a Tag component
## Size
medium

**Comment by schmulski** [comment]
@geekmaedchen great code! Please be so kind an use a feature branch next time!

**Comment by schmulski** [comment]
@geekmaedchen great code! Please be so kind an use a feature branch next time!
