### ISSUE TITLE
Route for both Filters

### ISSUE THREAD

**Issue by geekmaedchen** [geekmaedchen/pokelist#10]
## Value statement - a requirement, not a solution
As a **user** 
I need **the filters working** 
so that **I can see filtered lists and go back to all** 
## Description (Text, Scribble, Wireframe, Design)
Two Links in the Header on AllPokemonPage,
one Link to go back from each filter. 
Working Filters on each page.
## Acceptance criteria
- [x] Three different sites: All, Lucky and Want
- [x] back and forth directing
- [x] Filters are working
## Tasks
- [x] Implement React-Router-Dom
- [x] Make it work for a Homepage named "AllPokemon"
- [x] Route to a Site with a filtered list of wanted pokemon
- [x] Route to a second filter named Lucky
## Size
medium
