### ISSUE TITLE
Style image

### ISSUE THREAD

**Issue by geekmaedchen** [geekmaedchen/pokelist#11]
## Value statement - a requirement, not a solution
As a **user** 
I need **a smaller image** 
so that **I can see all information** 
## Acceptance criteria
- [x] Pokemon-Image is smaller and centered
## Tasks
- [x] style attribute on image max-width/height 100px
- [x] center the image
## Size
small
