### ISSUE TITLE
Improve Router

### ISSUE THREAD

**Issue by geekmaedchen** [geekmaedchen/pokelist#27]
## Value statement - a requirement, not a solution
As a **programmer** 
I need **a better structure of the router in App** 
so that **I can easily add new pages** 
## Description (Text, Scribble, Wireframe, Design)
<img width="425" alt="grafik" src="https://user-images.githubusercontent.com/53256699/70130803-7fdcf200-1681-11ea-84b2-4efcf3863b15.png">

## Acceptance criteria
- [x] Header is separated from sites

## Tasks
- [x] use one switch for the Header for startpage and the other
- [x] use another switch for the pages

## Size
small
