### ISSUE TITLE
More PokemonData

### ISSUE THREAD

**Issue by geekmaedchen** [geekmaedchen/pokelist#3]
## Value statement - a requirement, not a solution
As a **user** 
I need **for PokemonData** 
so that **I can catch them all** 
## Description (Text, Scribble, Wireframe, Design)
```
{
    number: #001,
    lucky: false,
    want: true,
      name: "Bulbasaur",
      region: "Kanto",
      types: ["grass", "poison"]
  },
```
## Acceptance criteria
- [x] 5-9 pokemon in list
## Tasks
- [x] create a .json-file with pokedex
- [x] make .json-file work with projekt
- [x] add more pokemon to pokedex.json
## Size
small
