### ISSUE TITLE
Filter of Want

### ISSUE THREAD

**Issue by geekmaedchen** [geekmaedchen/pokelist#4]
## Value statement - a requirement, not a solution
As a **user** 
I need **a filter** 
so that **I can see just the wanted pokemon** 
## Description (Text, Scribble, Wireframe, Design)
<img width="370" alt="grafik" src="https://user-images.githubusercontent.com/53256699/69734378-2596db00-112f-11ea-93f7-55d73c26e2ee.png">

## Acceptance criteria
- [x] Just the wanted pokemon are shown

## Tasks
- [x] create a toggle-state
- [x] write a toggle function
- [x] insert a button in a header
- [x] add a filter function on button-click

## Size
medium
