### ISSUE TITLE
Filter for Lucky

### ISSUE THREAD

**Issue by geekmaedchen** [geekmaedchen/pokelist#8]
## Value statement - a requirement, not a solution
As a **user** 
I need **a filter for lucky pokemon** 
so that **I can see which pokemon I have as lucky** 
## Description (Text, Scribble, Wireframe, Design)
Just like the Want-Filter...
## Acceptance criteria
- [x] There is a second link to a filtered list of lucky pokemon
- [x] Just the lucky pokemon are shown
- [x] There is a link which shows and redirects to "All Pokemon"
## Tasks
- [x] Copy and adjust FilterWant to FilterLucky
- [x] Make it work
## Size
small
