### ISSUE TITLE
Normalize PokedexData

### ISSUE THREAD

**Issue by geekmaedchen** [geekmaedchen/pokelist#9]
## Value statement - a requirement, not a solution
As a **user** 
I need **normalized data** 
so that **I have less redundancies in my data** 
## Acceptance criteria
- [x] pokedex.json is normalized
- [x] app is working like before
## Tasks
- [x] normalize pokedex.json
- [x] make app work again
## Size
medium
